"""
Alternative to src/extraction.py's single-pass "generate a JSON array of
claims" design, built to fix a bug that design can't fix by itself:
llama3.3:70b and llama3.1:70b both collapse a product description with
multiple distinct claims down to ~1-2 "representative" claims, almost
regardless of how many real claims are actually in the text -- confirmed
NOT a decoding/sampling artifact (identical output across temperature 0
and 0.2, and across grammar-constrained JSON on/off). The leading
hypothesis: an open-ended "list every claim you find" task implicitly
invites summarization/characterization of the whole description, which a
larger, more heavily-aligned model is prone to over-apply -- rather than
the "check this specific thing" framing that keeps a model from being able
to stop early.

This module avoids that framing entirely by never asking the model to
decide how many things to report. Three-step pipeline, one product at a
time:

  1. Segment the description into individual clauses in plain python3 (no
     model call). Since claim_text is therefore never generated by the
     model, this ALSO structurally eliminates the leak/hallucination bug
     class extraction.py fought all session (copying text from worked
     examples or from retrieved legal context into claim_text) -- there is
     no free-text field for the model to fill with the wrong source,
     because we already have the real clause text ourselves.
  2. One call classifies EVERY clause (not just the ones that look like
     claims) into one of the 11 golden-set categories or "not_a_claim".
     The response schema's array has minItems == maxItems == the number of
     clauses, so there is no way to submit a shorter list than the input --
     unlike extraction.py's open-ended array, the model cannot "stop early"
     without the response failing to validate against its own schema.
  3. A second call, over only the clauses flagged as real claims in step 2,
     assigns risk_level + risk_rationale -- kept separate from detection so
     the model isn't doing categorization and legal-severity judgment in
     the same pass.

Whether Ollama's grammar compiler actually ENFORCES minItems/maxItems on
array length is unverified as of this writing (Ollama's structured-output
support covers a subset of JSON Schema, and array-length bounds are less
commonly implemented than type/enum/required). Treat the schema constraint
as the primary mechanism but not a guaranteed one -- _check_cardinality
below is a hard backstop that flags (not silently fixes) a length mismatch,
same "soft prompt/schema + hard code backstop" pattern extraction.py uses
for its LOW-risk filter.

Deliberately NOT included in this first version, to isolate whether the
fixed-cardinality mechanism itself fixes the under-extraction bug before
adding more moving parts:
  - Legal grounding (the CANDIDATE LEGAL CONTEXT block extraction.py
    injects from compare_e5.py's retrieval). Can be added to the detection
    prompt later the same way if this pipeline earns its keep.
  - Per-clause few-shot examples with real Italian text -- given the
    lesson learned in extraction.py's SYSTEM_PROMPT, none of the prompts
    below use concrete example phrases; only bracketed placeholders.

Usage:
  python3 -m src.dissected_extraction --file coop_extraction_input.json \\
      --model llama3.3:70b --out results/coop/dissected_predictions.json

Output shape matches src/extraction.py's extract_from_file exactly (list of
{index, ean, name, claims, dropped_claims, elapsed_seconds}), so the same
gold-comparison scripts work against either pipeline's output unmodified.
"""

import json
import re
import time
from pathlib import Path
from typing import List, Optional, Tuple

import httpx

from .data import iter_records
from .extraction import (
    CLAIM_CATEGORIES,
    OLLAMA_URL,
    _split_claim_sentences,
)

NOT_A_CLAIM = "not_a_claim"

# --- Step 1: segmentation --------------------------------------------------
# _split_claim_sentences (extraction.py) already gives sentence-ish
# fragments, keyword-filtered to claim-adjacent content and stripped of
# mandatory disclosures/packaging badges -- reused as-is rather than
# duplicated, same convention src/knowledge/prepare_ads_chunks.py already
# follows. That alone isn't fine-grained enough for this pipeline's
# purpose, though: a single real sentence often runs together SEVERAL
# distinct claims via commas/conjunctions -- e.g. one sentence asserting
# "tradizionale, autentica ... dal 1820 la famiglia Grondona garantisce ...
# inimitabili ricette ... migliori ingredienti" is 4 separate claims in
# gold, not one. _split_into_clauses adds a second, finer pass on top.
#
# This finer split is a first-pass heuristic, explicitly flagged as a
# tuning point (per the design this module implements): splitting on every
# comma risks shredding a legitimate short list (e.g. an ingredient list)
# into fake "clauses". The length floor below (_MIN_CLAUSE_CHARS) is the
# current mitigation -- merge back into the previous fragment anything too
# short to plausibly be its own checkable assertion, rather than tuning the
# split points themselves. Revisit this heuristic first if segmentation
# quality (not detection accuracy) turns out to be the limiting factor.
_MIN_CLAUSE_CHARS = 12

_CLAUSE_SPLIT_RE = re.compile(r",\s+(?=[a-zà-ú0-9])|\s+(?:e|ed)\s+(?=[A-ZÀ-Ú])")


def _split_into_clauses(description: str) -> List[str]:
    """Sentence-level split (via _split_claim_sentences) followed by a
    finer comma/conjunction split within each sentence. See module +
    _CLAUSE_SPLIT_RE comments for why this is a tunable heuristic, not a
    principled parser."""
    sentences = _split_claim_sentences(description)
    clauses: List[str] = []
    for sentence in sentences:
        pieces = [p.strip() for p in _CLAUSE_SPLIT_RE.split(sentence) if p.strip()]
        merged: List[str] = []
        for piece in pieces:
            if merged and len(piece) < _MIN_CLAUSE_CHARS:
                merged[-1] = f"{merged[-1]}, {piece}"
            else:
                merged.append(piece)
        clauses.extend(merged if merged else [sentence])
    return clauses


# --- Step 2: detection + categorization, one call per product -------------
# No abstract "is this a claim?" gate: most sentences assert SOMETHING, so
# a yes/no framing over-triggers (this is the same failure CLAIM_KEYWORDS'
# own docstring in extraction.py warns about, one level up the pipeline).
# Instead the model picks exactly one label per clause from a closed list:
# the 11 real categories, or NOT_A_CLAIM for the explicit exclusion list
# below. Every category definition is abstract/English-only, no quoted
# Italian example phrases -- extraction.py's SYSTEM_PROMPT leaked exactly
# this kind of concrete example text into unrelated products' output.
_CATEGORY_DEFINITIONS = """- unsubstantiated_health_or_efficacy_claim: a health, wellness, or efficacy
  benefit claim about the product, not stated in EU-authorized regulatory
  wording.
- nutrition_content_claim: a nutrient-content claim tied to a fixed legal
  compositional threshold (fibre, vitamin, mineral, calorie content, etc.).
- misleading_composition_or_ingredient_claim: an OPTIONAL (not legally
  required) factual statement about what is or isn't among the product's
  ingredients or additives.
- misleading_authenticity_or_origin_claim: a claim about geographic origin,
  heritage, tradition, a founding date, or "made in" provenance.
- misleading_superiority_or_absolute_claim: absolute or superiority
  language about the product with no stated comparator or metric.
- unfair_comparison: a comparison against another product or an unstated,
  vague baseline.
- misleading_endorsement_claim: a named third-party body, institute, or
  professional group endorsing or approving the product.
- fake_or_unverified_label: a trust-mark, cause-marketing, or social/
  charitable-impact claim whose backing can't be confirmed from the text.
- environmental_unsubstantiated: a general or vague environmental-benefit
  claim about packaging, emissions, recyclability, or resource use -- NOT
  an offset-based carbon-neutrality claim (see next).
- offset_based_neutrality: specifically a carbon-neutral or net-zero claim
  based on offsetting emissions.
- irrelevant_claim: a real, specific, checkable statement that turns out to
  be a mandatory legal disclosure, EU-authorized wording used correctly, or
  a trivial non-actionable fact -- this is a REAL category, not the same as
  not_a_claim below."""

_NOT_A_CLAIM_EXCLUSIONS = """not_a_claim applies to a clause that is:
  - a bare ingredient, quantity, or nutrition-table number with no benefit
    or property asserted about it (e.g. a plain ingredient-list entry),
  - a storage, preparation, or usage instruction (how/where/when to use or
    keep the product), not an assertion the product possesses something,
  - subjective taste/experience language or a brand slogan with nothing
    checkable (puffery),
  - generic culinary description with no factual assertion attached.
Every clause gets exactly one label. If a clause both describes usage AND
asserts a benefit, classify the benefit assertion, not the usage framing."""

DETECTION_SYSTEM_PROMPT = f"""You are an EU consumer law analyst (UCPD, Dir. 2005/29/EC).
You will be given a numbered list of clauses extracted from one Italian
product's marketing text. Classify EVERY clause -- do not skip any, and do
not decide some are more important than others. Each clause gets exactly
one category from this list:

{_CATEGORY_DEFINITIONS}

{_NOT_A_CLAIM_EXCLUSIONS}

Disambiguation rule -- classify each clause on ITS OWN subject matter,
never by what clause it sits next to. A statement about what IS or ISN'T
in the product (ingredients, additives, allergens) is always
misleading_composition_or_ingredient_claim, even when adjacent to an
environmental clause. environmental_unsubstantiated is ONLY for packaging,
emissions, recyclability, or resource-use language.

Chemistry rule -- classify on checkability and authorization, never on
whether you believe the underlying chemistry is real. An ingredient
genuinely having a real chemical property is still
unsubstantiated_health_or_efficacy_claim if that property isn't asserted
in EU-authorized wording.

You will receive exactly N numbered clauses and must return exactly N
classification objects, one per clause_index, in the same order. This is a
hard requirement of the response format, not a suggestion."""


def _build_detection_schema(n: int) -> dict:
    return {
        "type": "object",
        "properties": {
            "classifications": {
                "type": "array",
                "minItems": n,
                "maxItems": n,
                "items": {
                    "type": "object",
                    "properties": {
                        "clause_index": {"type": "integer"},
                        "category": {"type": "string", "enum": CLAIM_CATEGORIES + [NOT_A_CLAIM]},
                    },
                    "required": ["clause_index", "category"],
                },
            }
        },
        "required": ["classifications"],
    }


def _build_detection_prompt(clauses: List[str]) -> str:
    numbered = "\n".join(f"{i + 1}. {clause}" for i, clause in enumerate(clauses))
    return f"""Classify each of these {len(clauses)} clauses. Return exactly {len(clauses)}
classification objects, clause_index 1 through {len(clauses)}, each with
one category from the system prompt's list.

CLAUSES:
{numbered}"""


# --- Step 3: risk-level classification, one call per product, only over --
# clauses step 2 flagged as real claims. Kept as a SEPARATE call from
# detection deliberately -- extraction.py's chemistry/certification-scope/
# MEDIUM-by-default rules (reused below) are legal-severity judgment calls,
# a different kind of reasoning from "which of 11 buckets does this belong
# to", and conflating the two in one pass is what extraction.py's original
# single-call design did.
RISK_SYSTEM_PROMPT = """You are an EU consumer law analyst (UCPD, Dir. 2005/29/EC).
You will be given a numbered list of claims, each already assigned a
category. Assign risk_level and a short risk_rationale to EVERY claim --
do not skip any.

risk_level: HIGH = directly contradicted by, or blacklisted regardless of,
the product's own stated facts (offset_based_neutrality is ALWAYS HIGH).
MEDIUM = a real, checkable benefit is asserted but nothing specific backs
THAT exact claim. LOW = trivially true, or backed by a real, specifically-
named certification/EU-authorized wording for THAT exact claim.

Certification scope rule -- a certification only lowers risk for the
SPECIFIC claim it names. A certification mentioned for one claim never
justifies LOW for a different, unrelated claim.

MEDIUM-by-default rule -- applies to every category except
nutrition_content_claim (that one has fixed legal thresholds, so it stays
LOW even when unverified from text -- no other category gets this
exception). For every other category, "nothing contradicts this" is NEVER
sufficient grounds for LOW -- an asserted-but-unbacked claim defaults to
MEDIUM regardless of how plausible it sounds. Reserve LOW only for a claim
you can point to real backing for.

You will receive exactly N numbered claims and must return exactly N risk
objects, one per claim_index, in the same order. This is a hard
requirement of the response format, not a suggestion."""

RISK_SCHEMA_ITEM_PROPERTIES = {
    "claim_index": {"type": "integer"},
    "risk_level": {"type": "string", "enum": ["HIGH", "MEDIUM", "LOW"]},
    "risk_rationale": {"type": "string"},
}


def _build_risk_schema(n: int) -> dict:
    return {
        "type": "object",
        "properties": {
            "risk_assessments": {
                "type": "array",
                "minItems": n,
                "maxItems": n,
                "items": {
                    "type": "object",
                    "properties": RISK_SCHEMA_ITEM_PROPERTIES,
                    "required": ["claim_index", "risk_level", "risk_rationale"],
                },
            }
        },
        "required": ["risk_assessments"],
    }


def _build_risk_prompt(flagged: List[Tuple[int, str, str]]) -> str:
    numbered = "\n".join(
        f"{i + 1}. [{category}] {clause}" for i, (_orig_idx, clause, category) in enumerate(flagged)
    )
    return f"""Assign risk_level + risk_rationale to each of these {len(flagged)} claims.
Return exactly {len(flagged)} risk objects, claim_index 1 through
{len(flagged)}.

CLAIMS:
{numbered}"""


def _ollama_json_call(
    system: str, prompt: str, schema: dict, model: str, temperature: float,
    num_predict: int, num_ctx: int, use_schema_grammar: bool,
) -> dict:
    response = httpx.post(
        OLLAMA_URL,
        json={
            "model": model,
            "system": system,
            "prompt": prompt,
            "stream": False,
            "format": schema if use_schema_grammar else "json",
            "options": {
                "temperature": temperature,
                "num_predict": num_predict,
                "num_ctx": num_ctx,
            },
        },
        timeout=600,
    )
    response.raise_for_status()
    raw = response.json()["response"]
    return json.loads(raw)


def _check_cardinality(items: List[dict], expected_n: int, index_key: str, label: str) -> None:
    """Hard backstop for the schema's minItems/maxItems, which Ollama's
    grammar compiler may or may not actually enforce (unverified -- see
    module docstring). Raises rather than silently truncating/padding, so a
    real cardinality miss surfaces as a failed record (visible in the
    --out run's failed.json) instead of quietly degrading back into the
    same under-extraction bug this pipeline exists to fix."""
    if len(items) != expected_n:
        raise ValueError(
            f"{label}: expected {expected_n} items, model returned {len(items)} -- "
            f"schema minItems/maxItems was not honored (see module docstring)"
        )
    seen = {item.get(index_key) for item in items}
    expected = set(range(1, expected_n + 1))
    if seen != expected:
        raise ValueError(f"{label}: {index_key} values {sorted(seen)} don't match expected 1..{expected_n}")


# Sized small deliberately: each output item here is ~10-15 tokens
# (an integer + one enum string), nothing like extraction.py's free-text
# claim_text. For a generous 30-clause product: 30 * 15 + 30 wrapper =~
# 480 -- rounded up hard for margin since this mechanism is new/unproven.
DETECTION_NUM_PREDICT = 1200
# system(~2500, category defs + rules) + schema(~250) + user prompt (numbered
# clauses, comparable to a pre-filtered description, ~200-800 words =~
# 300-1100 tok) + num_predict(1200) =~ 4250-5050 worst case -- rounded up.
DETECTION_NUM_CTX = 6000

# Each risk item is a bit larger (risk_rationale, up to 15 words =~ 20 tok)
# -- for 20 flagged claims: 20 * 40 + 30 =~ 830, rounded up for margin.
RISK_NUM_PREDICT = 1500
# system(~1200, shorter than detection -- no category defs) + schema(~150)
# + user prompt (numbered flagged claims, smaller than the full clause
# list) + num_predict(1500) =~ 3500-4000 worst case -- rounded up.
RISK_NUM_CTX = 5000


def dissect_claims(
    description: str, detection_model: str = "llama3.2", risk_model: Optional[str] = None,
    temperature: float = 0, use_schema_grammar: bool = True,
    risk_use_schema_grammar: Optional[bool] = None,
    detection_num_predict_override: Optional[int] = None, detection_num_ctx_override: Optional[int] = None,
    risk_num_predict_override: Optional[int] = None, risk_num_ctx_override: Optional[int] = None,
) -> dict:
    """Runs the full 3-step pipeline for one product's description.

    detection_model/risk_model let the two calls use different models --
    the detection call (categorize every clause) and the risk call (assign
    HIGH/MEDIUM/LOW) are already independent Ollama calls, just forced onto
    the same model before this. Motivated by measurements on
    golden/samples/canonical/sample_coop.json: plain llama3.3:70b has the
    best raw recall/F1 of any single model tried, while deepseek-r1:70b
    (ungrounded) has the best category accuracy and lowest false-positive
    rate -- pairing a high-recall detector with a more disciplined risk
    judge is untested but well-motivated by those two models' distinct
    error profiles. risk_model=None (default) reuses detection_model,
    preserving every prior single-model run's exact behavior.

    risk_use_schema_grammar / *_num_predict_override / *_num_ctx_override:
    a reasoning risk_model needs its own budget/grammar setting independent
    of the detection call's -- see extraction.py's full_grounding_deepseek
    experiment for why grammar-constrained decoding and an undersized
    num_predict both broke down on a model with a <think> preamble.
    Defaults (None) reuse use_schema_grammar and the module-level
    RISK_NUM_PREDICT/RISK_NUM_CTX constants, i.e. current behavior.

    Returns {"claims": [...], "excluded_clauses": [...]} -- claims entries
    have {claim_text, category, risk_level, risk_rationale}, matching
    extraction.py's claim shape exactly. excluded_clauses are the clauses
    step 2 classified as not_a_claim (claim_text + category="not_a_claim"),
    kept visible for audit rather than silently discarded, same philosophy
    as extraction.py's dropped_claims.

    Makes 0-2 Ollama calls: 0 if there are no claim-adjacent clauses at
    all, 1 if clauses exist but none are flagged as real claims (skips the
    risk-assessment call entirely), 2 otherwise.
    """
    risk_model = risk_model or detection_model
    risk_use_schema_grammar = use_schema_grammar if risk_use_schema_grammar is None else risk_use_schema_grammar
    detection_num_predict = detection_num_predict_override or DETECTION_NUM_PREDICT
    detection_num_ctx = detection_num_ctx_override or DETECTION_NUM_CTX
    risk_num_predict = risk_num_predict_override or RISK_NUM_PREDICT
    risk_num_ctx = risk_num_ctx_override or RISK_NUM_CTX

    clauses = _split_into_clauses(description)
    if not clauses:
        return {"claims": [], "excluded_clauses": []}

    detection = _ollama_json_call(
        system=DETECTION_SYSTEM_PROMPT,
        prompt=_build_detection_prompt(clauses),
        schema=_build_detection_schema(len(clauses)),
        model=detection_model, temperature=temperature,
        num_predict=detection_num_predict, num_ctx=detection_num_ctx,
        use_schema_grammar=use_schema_grammar,
    )
    classifications = detection.get("classifications", [])
    _check_cardinality(classifications, len(clauses), "clause_index", "detection")
    classifications.sort(key=lambda c: c["clause_index"])

    excluded_clauses = []
    flagged: List[Tuple[int, str, str]] = []  # (original clause index, clause text, category)
    for c in classifications:
        idx = c["clause_index"] - 1
        clause_text = clauses[idx]
        category = c["category"]
        if category == NOT_A_CLAIM:
            excluded_clauses.append({"claim_text": clause_text, "category": NOT_A_CLAIM})
        else:
            flagged.append((idx, clause_text, category))

    if not flagged:
        return {"claims": [], "excluded_clauses": excluded_clauses}

    risk = _ollama_json_call(
        system=RISK_SYSTEM_PROMPT,
        prompt=_build_risk_prompt(flagged),
        schema=_build_risk_schema(len(flagged)),
        model=risk_model, temperature=temperature,
        num_predict=risk_num_predict, num_ctx=risk_num_ctx,
        use_schema_grammar=risk_use_schema_grammar,
    )
    assessments = risk.get("risk_assessments", [])
    _check_cardinality(assessments, len(flagged), "claim_index", "risk assessment")
    assessments.sort(key=lambda a: a["claim_index"])

    claims = []
    for (_, clause_text, category), assessment in zip(flagged, assessments):
        claims.append({
            "claim_text": clause_text,
            "category": category,
            "risk_level": assessment["risk_level"],
            "risk_rationale": assessment["risk_rationale"],
        })
    return {"claims": claims, "excluded_clauses": excluded_clauses}


def _validate_dissected_claims(claims: List[dict]) -> Tuple[List[dict], List[dict]]:
    """Same LOW-risk drop policy as extraction.py's _validate_claims, kept
    as a separate function (not imported) since this pipeline's claims
    never have an empty claim_text to also filter -- clause text comes
    from our own segmentation, never from the model."""
    valid, dropped = [], []
    for c in claims:
        if (c.get("risk_level") or "").upper() == "LOW":
            dropped.append({**c, "_dropped_reason": "risk_level=LOW (filtered by policy)"})
        else:
            valid.append(c)
    return valid, dropped


def dissect_from_file(
    filename: str, detection_model: str = "llama3.2", risk_model: Optional[str] = None,
    temperature: float = 0, use_schema_grammar: bool = True,
    risk_use_schema_grammar: Optional[bool] = None,
    detection_num_predict_override: Optional[int] = None, detection_num_ctx_override: Optional[int] = None,
    risk_num_predict_override: Optional[int] = None, risk_num_ctx_override: Optional[int] = None,
) -> Tuple[List[dict], List[dict]]:
    records = list(iter_records(filename))
    total = len(records)
    results = []
    failed = []
    total_dropped = 0
    run_start = time.monotonic()

    for i, (idx, record) in enumerate(records, 1):
        name = record.get("name", f"record {idx}")
        print(f"[{i}/{total}] {name}", end=" ... ", flush=True)

        call_start = time.monotonic()
        try:
            result = dissect_claims(
                description=record["description"], detection_model=detection_model, risk_model=risk_model,
                temperature=temperature, use_schema_grammar=use_schema_grammar,
                risk_use_schema_grammar=risk_use_schema_grammar,
                detection_num_predict_override=detection_num_predict_override,
                detection_num_ctx_override=detection_num_ctx_override,
                risk_num_predict_override=risk_num_predict_override,
                risk_num_ctx_override=risk_num_ctx_override,
            )
            elapsed = time.monotonic() - call_start

            claims, dropped = _validate_dissected_claims(result["claims"])
            # excluded_clauses (not_a_claim) surfaced alongside LOW-risk drops
            # so every clause the segmentation step produced is visible
            # somewhere in the output -- nothing vanishes unaudited.
            dropped = dropped + [
                {**c, "_dropped_reason": "not_a_claim"} for c in result["excluded_clauses"]
            ]
            total_dropped += len(dropped)
            results.append({
                "index": idx,
                "ean": record.get("ean"),
                "name": record.get("name"),
                "claims": claims,
                "dropped_claims": dropped,
                "elapsed_seconds": round(elapsed, 2),
            })
            suffix = f" ({len(dropped)} dropped)" if dropped else ""
            print(f"{len(claims)} claims found{suffix} [{elapsed:.1f}s]")

        except Exception as e:
            elapsed = time.monotonic() - call_start
            print(f"FAILED after {elapsed:.1f}s: {e}")
            failed.append({"index": idx, "ean": record.get("ean"), "name": name, "error": str(e)})
            time.sleep(2)
            continue

    total_elapsed = time.monotonic() - run_start
    avg_per_record = total_elapsed / total if total else 0
    print(f"\nDone: {len(results)} ok, {len(failed)} failed, {total_dropped} claims dropped by validation")
    print(f"Total time: {total_elapsed:.1f}s ({total_elapsed/60:.1f} min), avg {avg_per_record:.1f}s/record")
    if failed:
        print("Failed records:")
        for f in failed:
            print(f"  [{f['index']}] {f['name']} — {f['error']}")

    return results, failed


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--file", required=True, help="filename in data/raw/, e.g. coop_extraction_input.json")
    parser.add_argument("--model", default="llama3.2", help="model for the detection/classification call. "
        "Also used for risk assessment unless --risk-model is given.")
    parser.add_argument(
        "--risk-model", default=None,
        help="separate model for the risk-level (HIGH/MEDIUM/LOW) call, distinct from --model's "
        "detection/classification call. Defaults to --model. Motivated by measurements showing "
        "plain llama3.3:70b has the best recall/F1 while deepseek-r1:70b (ungrounded) has the best "
        "category accuracy/lowest false-positive rate -- untested pairing, not a proven combo.",
    )
    parser.add_argument("--out", default=None, help="optional output path for results json")
    parser.add_argument("--temperature", type=float, default=0)
    parser.add_argument(
        "--no-schema-grammar", dest="use_schema_grammar", action="store_false",
        help="disable grammar-constrained decoding (falls back to loose 'format': 'json') for BOTH "
        "calls unless --risk-no-schema-grammar/--risk-schema-grammar overrides the risk call "
        "specifically. The minItems/maxItems cardinality constraint this pipeline relies on is "
        "grammar-only, so this flag also removes that mechanism.",
    )
    parser.add_argument(
        "--risk-no-schema-grammar", dest="risk_use_schema_grammar", action="store_false", default=None,
        help="disable grammar-constrained decoding for the risk call only, independent of --model's "
        "setting -- needed if --risk-model is a reasoning model (grammar-constrained decoding likely "
        "conflicts with a <think> preamble, same issue found in extraction.py's full-grounding test).",
    )
    parser.add_argument(
        "--risk-schema-grammar", dest="risk_use_schema_grammar", action="store_true", default=None,
        help="force grammar-constrained decoding for the risk call only, independent of --model's setting.",
    )
    parser.add_argument(
        "--risk-num-predict", type=int, default=None,
        help="override RISK_NUM_PREDICT (1500) for the risk call -- needed for a reasoning --risk-model, "
        "whose <think> trace before HIGH/MEDIUM/LOW has an unmeasured length that tiny default won't fit.",
    )
    parser.add_argument(
        "--risk-num-ctx", type=int, default=None,
        help="override RISK_NUM_CTX (5000) for the risk call -- see --risk-num-predict.",
    )
    args = parser.parse_args()

    results, failed = dissect_from_file(
        args.file, detection_model=args.model, risk_model=args.risk_model, temperature=args.temperature,
        use_schema_grammar=args.use_schema_grammar, risk_use_schema_grammar=args.risk_use_schema_grammar,
        risk_num_predict_override=args.risk_num_predict, risk_num_ctx_override=args.risk_num_ctx,
    )

    print(f"\nProcessed {len(results)} products")
    total_claims = sum(len(r["claims"]) for r in results)
    print(f"Total claims extracted: {total_claims}")
    print(f"Failed records: {len(failed)}")

    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(results, indent=2, ensure_ascii=False))
        print(f"Saved to {args.out}")

        if failed:
            fail_path = out_path.parent / "failed.json"
            fail_path.parent.mkdir(parents=True, exist_ok=True)
            fail_path.write_text(json.dumps(failed, indent=2, ensure_ascii=False))
            print(f"Failed records saved to {fail_path}")
    else:
        print(json.dumps(results[:2], indent=2, ensure_ascii=False))
